apiVersion: v1
kind: Service
metadata:
  name: naga-proxy
spec:
  selector:
    app: naga-proxy
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  externalTrafficPolicy: Local
  type: LoadBalancer
  