apiVersion: v1
kind: Service
metadata:
  name: naga-proxy
spec:
  selector:
    app: naga-proxy
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  externalIPs:
    - 147.45.105.244
    - 0.0.0.0
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  