apiVersion: v1
kind: Service
metadata:
  name: naga-proxy
  annotations:
    metallb.universe.tf/loadBalancerIPs: 147.45.105.244
spec:
  selector:
    app: naga-proxy
  ports:
    - port: 80
      nodePort: 30000
  type: NodePort