apiVersion: v1
kind: Service
metadata:
  name: naga-proxy
spec:
  selector:
    app: naga-proxy
  ports:
    - port: 80
      targetPort: 80
  externalIPs:
    - 147.45.105.244
  externalTrafficPolicy: Local
  type: LoadBalancer
  