server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    pipeline_stages:
      - match:
          selector: '{job="nginx"}'
          stages:
            - json:
                expressions:
                  timestamp: time
            - timestamp:
                source: timestamp
                format: RFC3339

    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          hostname: HOSTNAME
          __path__: /var/log/*.access.log

      - targets:
          - localhost
        labels:
          job: nginx
          hostname: HOSTNAME
          __path__: /var/log/*.error.log