apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: naga-proxy
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: g-core
                port:
                  number: 80
                