scrape_configs:
  - job_name: 'cherry-core monitor'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cherry-core.cherry:3001']

  - job_name: 'cherry-outside monitor'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cherry-outside.cherry:3001']

  - job_name: 'cherry-production monitor'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cherry-production.cherry:3001' ]

  - job_name: 'grafana monitor'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']