scrape_configs:
  - job_name: 'g-core monitor'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['g-core:1210']

  - job_name: 'grafana monitor'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']