scrape_configs:
  - job_name: 'cherry-core monitor'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cherry-core.cherry']

  - job_name: 'cherry-outside monitor'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cherry-outside.cherry']

  - job_name: 'cherry-production monitor'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cherry-production.cherry' ]

  - job_name: 'grafana monitor'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana']

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: [ 'kube-state-metrics.kube-metrics.svc.cluster.local:8080' ]