apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      name: tempo
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: vikazeni/tempo:latest
          imagePullPolicy: Always
      restartPolicy: Always
      