apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      name: export
      port: 3200
    - protocol: TCP
      name: spring
      port: 9411
  type: ClusterIP
  