name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs: {}

    
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout naga
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Naga-proxy
      uses: docker/build-push-action@v5
      with:
        context: ./docker/naga-proxy
        file: ./docker/naga-proxy/Dockerfile
        push: true
        tags: vikazeni/naga-proxy:latest

    - name: Grafana
      uses: docker/build-push-action@v5
      with:
        context: ./docker/grafana
        file: ./docker/grafana/Dockerfile
        push: true
        tags: vikazeni/grafana:latest

    - name: Loki
      uses: docker/build-push-action@v5
      with:
        context: ./docker/loki
        file: ./docker/loki/Dockerfile
        push: true
        tags: vikazeni/loki:latest

    - name: Tempo
      uses: docker/build-push-action@v5
      with:
        context: ./docker/tempo
        file: ./docker/tempo/Dockerfile
        push: true
        tags: vikazeni/tempo:latest

    - name: Prometheus
      uses: docker/build-push-action@v5
      with:
        context: ./docker/prometheus
        file: ./docker/prometheus/Dockerfile
        push: true
        tags: vikazeni/prometheus:latest

    - name: Promtail
      uses: docker/build-push-action@v5
      with:
        context: ./docker/promtail
        file: ./docker/promtail/Dockerfile
        push: true
        tags: vikazeni/promtail:latest
